<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hasenbalg_adventcal"
 *
 * Auto generated by Extension Builder 2020-11-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Advent Calendar',
    'description' => 'An advent calendar for TYPO3',
    'category' => 'plugin',
    'author' => 'Frank Hasenbalg',
    'author_email' => 'frank@hasenbalg.org',
    'state' => 'stable',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
